# docker network create --driver nat network-name

version: '3.8'
services:
  mongodb:
    image: mongodb/mongodb-community-server:7.0.1-ubuntu2204
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
volumes:
  mongodb-data:
